### ISSUE TITLE
结束功能无法使用

### ISSUE THREAD

**Issue by nansou520** [noneplugin/nonebot-plugin-minesweeper#9]
游戏运行时,发送 /结束 机器人无法正常结束游戏

**Comment by MeetWq** [comment]
有日志吗

**Comment by nansou520** [comment]
![image](https://github.com/user-attachments/assets/307f7941-d0aa-4144-9eeb-156521834e7a)
发送 /结束 (包括结束游戏,结束扫雷等)什么后台反应也没有
挖开,标记,查看等可以正常使用
(我擅自把rule=to_me去掉了应该没啥事吧)

**Comment by MeetWq** [comment]
看看你改了哪里
我这边没问题啊

**Comment by nansou520** [comment]
![image](https://github.com/user-attachments/assets/8dac08b1-cfb2-4252-ba1d-910d60d1fe08)
就只改了这里
(后面我害怕是优先级的问题还把block给去了)
我好奇的是,"查看"和"结束"这俩格式一模一样,但是查看能用,结束用不了

**Comment by nansou520** [comment]
我说去掉的rule=to_me是前面那个,是一开始触发"扫雷"的那边,不过那个能用

**Comment by MeetWq** [comment]
把日志等级调成debug看看？

**Comment by nansou520** [comment]
呃呃我找到问题所在了
我猜单词的结束命令优先级设置的5,扫雷的结束优先级设置的8,所以被猜单词block掉了
(虽然应该是没有通过猜单词的rule判定的后台也没有弹出猜单词的触发器,不解,但是把这俩优先级调成一样的确实解决问题了)
还是谢谢大佬

**Comment by MeetWq** [comment]
> 呃呃我找到问题所在了 我猜单词的结束命令优先级设置的5,扫雷的结束优先级设置的8,所以被猜单词block掉了 (虽然应该是没有通过猜单词的rule判定的后台也没有弹出猜单词的触发器,不解,但是把这俩优先级调成一样的确实解决问题了) 还是谢谢大佬


这是 nonebot-plugin-alconna 的 bug，已经反馈给作者修了 https://github.com/nonebot/plugin-alconna/commit/d44fcc3a4a523a972e4be0eb90a5b68a41ffb700

**Comment by nansou520** [comment]
是的,更改优先级后扫雷的结束能用了,猜单词的结束又失灵了
最后把猜单词的触发器换成on_command才得以解决
